### ISSUE TITLE
Can't Get the Library to Work

### ISSUE THREAD

**Issue by oxters168** [oxters168/DepotDownloader#1]
Sorry Senioi, apparently I had issues set to off in the settings. I just turned them on. Here is a link to the comment where you wrote your issue:

https://github.com/oxters168/DepotDownloader/commit/20f23a9035b2112f2aea3431351d1e11865e0811#commitcomment-35201126

A few questions I have:

What errors are you getting?
What is the framework version you are targeting?
Also can you post the messages you received from Debug Log.

From what I have to work with though, I think the culprit might be that the log in function isn't finishing before you start downloading since you are in an async function. Maybe I can make an async log in function so it can be awaited as well, but just to make sure that that is the problem, an error would be handy.

**Comment by senioi** [comment]
@oxters168 
Thank you for your reply.
 framework version :  .net core 2.1
I am trying to create a simple dedicated server management tool
It is used to automatically update the game program as well as workshop mod files.
From the debug log, it seems that it is not logged in.

Code:

>     static async Task Main()
>         {
>             DebugLog.AddListener(new DebugListener());
>             DebugLog.Enabled = true;
> 
>             ConfigStore.LoadFromFile(Path.Combine(Directory.GetCurrentDirectory(), "DepotDownloader.config"));
>             SteamClient steamClient = new SteamClient();
>             CallbackManager callbacks = new CallbackManager(steamClient);
>             Steam3Session steam3 = new Steam3Session(steamClient, callbacks);
> 
>              steam3.LoginAs(new SteamUser.LogOnDetails()
>             {
>                 Username = "some_account",
>                 Password = "password",
>                 ShouldRememberPassword = false,
>             });
>             await ContentDownloader.DownloadApp(steam3, "Papers", 304930);
>             ulong pubFile = 1867076017;
>             Console.WriteLine("Login Done. started:{0}", pubFile);
>             await ContentDownloader.DownloadPubfileAsync(steam3, pubFile);
> 
>         }
> 

Logs:

> Debug - Steam3Session: Connecting to Steam3...
> Debug - ServerList: Resolving server list
> Debug - ServerList: Server list provider had no entries, will query SteamDirectory
> Debug - CMClient: Sent -> EMsg: ClientPICSAccessTokenRequest (Proto: True)
> Debug - ServerList: Resolved 200 servers
> Debug - ServerList: Next server candidiate: 203.80.149.68:27018 (Tcp)
> Debug - TcpConnection: Connecting to 203.80.149.68:27018...
> Debug - TcpConnection: Connected to 203.80.149.68:27018
> Debug - EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
> Debug - EnvelopeEncryptedConnection: Encryption result: OK

**Comment by oxters168** [comment]
It seems to be as I thought, the log in function is not completing before the next function gets called. So I just pushed a commit to help fix this issue. I made a function called LoginAsAsync. Use that instead of LoginAs, and add to it await. I'm not entirely sure if it will work, since for some reason for me it still seems to end early. Then again I'm not very well acquainted with asynchronous functions. I hope this will fix it though.

**Comment by senioi** [comment]
I am trying to synchronize/asynchronous
I think the code I wrote is wrong.
Does this code require a login action?
Please give me a correct sample code to learn, if you can.

```
using System;
using System.IO;
using SteamKit2;
using DepotDownloader;

namespace UpdateMyGameServer
{
    class Program
    {
        static void Main(string[] args)
        {
            DebugLog.AddListener(new DebugListener());
            DebugLog.Enabled = true;

            ConfigStore.LoadFromFile(Path.Combine(Directory.GetCurrentDirectory(), "DepotDownloader.config"));
            SteamClient steamClient = new SteamClient();
            CallbackManager callbacks = new CallbackManager(steamClient);
            Steam3Session steam3 = new Steam3Session(steamClient, callbacks);

              steam3.LoginAs(new SteamUser.LogOnDetails()
            {
                Username = "user",
                Password = "password",
                ShouldRememberPassword = false,
            });
            if (steam3.isLoggingIn)
            {
                Console.WriteLine("start download");
                ContentDownloader.DownloadApp(steam3, "Papers", 304930).Wait();
                ulong pubFile = 1867076017;
                Console.WriteLine("Mods started:{0}", pubFile);
                ContentDownloader.DownloadPubfileAsync(steam3, pubFile).Wait();
            }
            
        }
    }
}
```



Logs:

> Debug - Steam3Session: Connecting to Steam3...
> Debug - ServerList: Resolving server list
> Debug - ServerList: Server list provider had no entries, will query SteamDirectory
> start download
> Debug - CMClient: Sent -> EMsg: ClientPICSAccessTokenRequest (Proto: True)
> Debug - ServerList: Resolved 200 servers
> Debug - ServerList: Next server candidiate: 153.254.86.29:27017 (Tcp)
> Debug - TcpConnection: Connecting to 153.254.86.29:27017...
> Debug - TcpConnection: Connected to 153.254.86.29:27017
> Debug - EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
> Debug - EnvelopeEncryptedConnection: Encryption result: OK
> Debug - CMClient: <- Recv'd EMsg: ClientLogOnResponse (751) (Proto: False)
> Debug - CMClient: Got non-proto logon response, this is indicative of no logon attempt after connecting.
> Debug - TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
>    at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>    at System.IO.BinaryReader.ReadUInt32()
>    at SteamKit2.TcpConnection.ReadPacket() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 278
>    --- End of inner exception stack trace ---
>    at SteamKit2.TcpConnection.ReadPacket() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 283
>    at SteamKit2.TcpConnection.NetLoop() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 241

**Comment by oxters168** [comment]
The problem is that the log in function doesn't wait until log in is done. I made a commit recently which hopefully fixes that. If you want to try it, get the latest commit (pull or download) then try this code:

```
static async Task Main()
    {
        DebugLog.AddListener(new DebugListener());
        DebugLog.Enabled = true;

        ConfigStore.LoadFromFile(Path.Combine(Directory.GetCurrentDirectory(), "DepotDownloader.config"));
        SteamClient steamClient = new SteamClient();
        CallbackManager callbacks = new CallbackManager(steamClient);
        Steam3Session steam3 = new Steam3Session(steamClient, callbacks);

         await steam3.LoginAsAsync(new SteamUser.LogOnDetails()
        {
            Username = "some_account",
            Password = "password",
            ShouldRememberPassword = false,
        });
        await ContentDownloader.DownloadApp(steam3, "Papers", 304930);
        ulong pubFile = 1867076017;
        Console.WriteLine("Login Done. started:{0}", pubFile);
        await ContentDownloader.DownloadPubfileAsync(steam3, pubFile);

    }
```

If that still doesn't work or you don't want to try the latest commit, there is an event you can use in Steam3Session called onLoggedOn. So you would put the code you want to happen after the log on in the callback you add to the event.

**Comment by senioi** [comment]
```
        static async Task Main()
        {
            DebugLog.AddListener(new DebugListener());
            DebugLog.Enabled = true;

            ConfigStore.LoadFromFile(Path.Combine(Directory.GetCurrentDirectory(), "DepotDownloader.config"));
            SteamClient steamClient = new SteamClient();
            CallbackManager callbacks = new CallbackManager(steamClient);
            Steam3Session steam3 = new Steam3Session(steamClient, callbacks);

            await steam3.LoginAsAsync(new SteamUser.LogOnDetails()
            {
                Username = "some_accont",
                Password = "password",
                ShouldRememberPassword = false,
            });
            Console.WriteLine("Login Done.");

        }
```

Logs:

> Debug - Steam3Session: Connecting to Steam3...
> Debug - ServerList: Resolving server list
> Debug - ServerList: Server list provider had no entries, will query SteamDirectory
> Debug - ServerList: Resolved 200 servers
> Debug - ServerList: Next server candidiate: 180.101.192.249:27017 (Tcp)
> Debug - TcpConnection: Connecting to 180.101.192.249:27017...
> Debug - TcpConnection: Connected to 180.101.192.249:27017
> Debug - EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
> Debug - EnvelopeEncryptedConnection: Encryption result: OK
> Debug - CMClient: <- Recv'd EMsg: ClientLogOnResponse (751) (Proto: False)
> Debug - CMClient: Got non-proto logon response, this is indicative of no logon attempt after connecting.
> Debug - TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
>    at System.IO.__Error.EndOfFile()
>    at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>    at System.IO.BinaryReader.ReadUInt32()
> at SteamKit2.TcpConnection.ReadPacket() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 278
> --- End of inner exception stack trace ---
> at SteamKit2.TcpConnection.ReadPacket() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 283
> at SteamKit2.TcpConnection.NetLoop() in B:\Outlearn\Other\SteamKit_oxters168\SteamKit2\SteamKit2\NetOutlearning\Steam3\TcpConnection.cs:line 241

**Comment by senioi** [comment]
I'm sorry to have taken so much of your time.

**Comment by oxters168** [comment]
Hey it's alright, no need to be sorry. I hope I'll be able to fix this issue soon. I can't seem to make heads of it at the moment. It is really late here so I'm going to have to go to bed for now. I'll look at it first thing tomorrow and hopefully give you a good solution.

**Comment by oxters168** [comment]
Me being the idiot I am, I forgot to include CallbackManager's RunWaitCallbacks function. Here is the code that worked for me:

```
        static bool isRunning = true;
        static async Task Main(string[] args)
        {
            DebugLog.AddListener(new DebugListener());
            DebugLog.Enabled = true;

            ConfigStore.LoadFromFile(Path.Combine(Directory.GetCurrentDirectory(), "DepotDownloader.config"));
            SteamClient steamClient = new SteamClient();
            CallbackManager callbacks = new CallbackManager(steamClient);
            Steam3Session steam3 = new Steam3Session(steamClient, callbacks);

            callbacks.Subscribe<SteamClient.DisconnectedCallback>(DisconnectedCallback);

            Task.Run(() => { RunCallbacks(callbacks); });

            await steam3.LoginAsAsync(new SteamUser.LogOnDetails()
            {
                Username = "abc",
                Password = "123",
                ShouldRememberPassword = false,
            });

            Console.WriteLine("Login Done.");
        }

        private static void RunCallbacks(CallbackManager callbackManager)
        {
            // create our callback handling loop
            while (isRunning)
            {
                // in order for the callbacks to get routed, they need to be handled by the manager
                callbackManager.RunWaitCallbacks(TimeSpan.FromSeconds(1));
            }
        }

        private static void DisconnectedCallback(SteamClient.DisconnectedCallback connected)
        {
            DebugLog.WriteLine("Steam3Session", " Disconnected from Steam");
            isRunning = false;
        }
```

**Comment by senioi** [comment]
@oxters168 Thanks for your help.
You have donate page?
Let me treat you to a cup of coffee.

**Comment by oxters168** [comment]
I'm glad I was able to get it working for you! I don't have a donate page, getting it to work is reward enough :)
